openapi: 3.0.1
info:
  title: apigw-a2a-multi-agents-async-server
  description: API Gateway endpoints for A2A Server (for multi-agent async demo)
  version: 1.0.0

components:
  schemas:
    error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    uid:
      type: object
      properties:
        uid:
          type: string
  responses:
    error:
      description: internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"
          example:
            code: 500
            message: "unable to retrieve message"

paths:
  /{proxy+}:
    x-amazon-apigateway-any-method:
      summary: strands agents acting as A2A server
      description: endpoint for strands agents a2a server
      responses:
        200:
          description: ok
        500:
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-amazon-apigateway-integration:
        httpMethod: POST
        payloadFormatVersion: "1.0"
        passthroughBehavior: "when_no_match"
        responses:
          default:
            statusCode: 200
        type: AWS_PROXY
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${A2AServerFunction}/invocations"